gift_homepage:
    path:     /
    defaults: { _controller: giftBundle:Default:index }
gift_createEvent:
    path:     /new-event
    defaults: { _controller: giftBundle:Default:createEvent }
gift_myAccount:
    path:     /my-account
    defaults: { _controller: giftBundle:Default:myAccount }
gift_event:
    path:     /event-detail/{token}
    defaults: { _controller: giftBundle:Default:displayEvent}
gift_invitation:
    path:     /invitation/{token}
    defaults: { _controller: giftBundle:Default:invitation}
gift_invited:
    path:     /event/{sharedToken}
    defaults: { _controller: giftBundle:UserEvent:createUserEvent}